spring.application.name=Financial_backend

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finance_portfolio_db}
    spring.datasource.username=${SPRING_DATASOURCE_USERNAME:choinu}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT
jwt.secret=${JWT_SECRET:your-super-secret-key-that-is-at-least-256-bits-long-replace-this}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Scheduling
spring.task.scheduling.enabled=true

# Logging
logging.level.root=WARN
logging.level.com.Financial_backend=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{HH:mm:ss} %highlight(%-5level) %cyan(%-30logger{30}) %msg%n

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pewdiepiepie661@gmail.com
spring.mail.password=bvtnjhldrezzfhxy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App URL
app.base-url=${APP_BASE_URL:http://localhost:5173}

# Port
server.port=${SERVER_PORT:8080}



