spring.application.name=Financial_backend


spring.datasource.url=jdbc:postgresql://localhost:5432/finance_portfolio_db
spring.datasource.username=choinu
spring.datasource.password=



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#server.port= 8081


#jwt secret
jwt.secret=your-super-secret-key-that-is-at-least-256-bits-long-replace-this

# Access token: 15 minutes (short ? safe for financial app)
jwt.access-token-expiration=900000

# Refresh token: 7 days (long ? stored in DB so can be revoked anytime)
jwt.refresh-token-expiration=604800000

# ??Scheduling (for refresh token cleanup job)
spring.task.scheduling.enabled=true

# ?? Logging
logging.level.root=WARN
logging.level.com.Financial_backend=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{HH:mm:ss} %highlight(%-5level) %cyan(%-30logger{30}) %msg%n



# ?? Email Config (using Gmail SMTP) ??
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pewdiepiepie661@gmail.com
spring.mail.password=dfjkfargeakenyvo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ?? App URL (used in the email link) ??
app.base-url=http://localhost:5173