spring.application.name=Financial_backend


spring.datasource.url=jdbc:postgresql://localhost:5432/finance_portfolio_db
spring.datasource.username=choinu
spring.datasource.password=



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#server.port= 8081


jwt.secret ="a544738394f93b3c6522c7a9c9dbe107f428e26e6a362c8b7d186b45843309e6";
jwt.expiration= 86400000